#简体中文：zh-CN
#English: en-US
Language: en-US

#启用潮汐系统的世界(名字)
#Worlds with tide system on (name)
#Worlds:
#  - world
Worlds: []

#是否在控制台显示计算进度
#whether to display the calculation progress in the console
DisplayCalcInfo: true

#每tick允许的最长计算时间，单位毫秒
#The longest calculation time allowed per tick, in milliseconds
MaxTimeConsume: 10

#潮汐时刻
#Tide time
#每一个小时对应1000tick，早上七点为0tick，依次类推，比如说早上八点为1000tick
#Every hour corresponds to 1000 tick, 0 tick at 7:00 in the morning, and so on, for example, 1000 tick at 8:00 in the morning
#Level表示距离初始海平面的潮汐高度差，正数表示高于初始海平面，负数表示低于初始海平面
#Level represents the tidal height difference from the initial sea level,
#a positive number means higher than the initial sea level, and a negative number means lower than the initial sea level
#非特殊世界不建议高于初始海平面，容易水漫金山
#Non-special world is not recommended to be higher than the initial sea level, easy causing flood
Tide:
  0:
    level: 0
  1000:
    level: 0
  2000:
    level: 0
  3000:
    level: -1
  4000:
    level: -1
  5000:
    level: -1
  6000:
    level: -2
  7000:
    level: -2
  8000:
    level: -2
  9000:
    level: -3
  10000:
    level: -3
  11000:
    level: -3
  12000:
    level: -2
  13000:
    level: -2
  14000:
    level: -2
  15000:
    level: -1
  16000:
    level: -1
  17000:
    level: -1
  18000:
    level: 0
  19000:
    level: 0
  20000:
    level: 0
  21000:
    level: 0
#    level: 1
  22000:
    level: 0
#    level: 1
  23000:
    level: 0
#    level: 1

#Debug
Debug: false