name: Tide
version: '${project.version}'
main: cn.goldenpotato.tide.Tide
api-version: 1.14
authors: [ goldenpotato137@gmail.com ]
load: STARTUP
loadbefore:
  - Multiverse-Core
softdepend:
  - PlaceholderAPI
commands:
  tide:
    description: "Tide"
    usage: "/tide"